### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by anthouny** [securechicken/homebridge-freebox-player-delta#1]
Quelles sont les phrases que nous pouvons dire à Siri pour qu'il contrôle le player ?

Comment faire pour modifier le volume ?

**Comment by anthouny** [comment]
Serais-ce possible de discuter ensemble de ce plugin ?

**Comment by DavidMaarek** [comment]
> Quelles sont les phrases que nous pouvons dire à Siri pour qu'il contrôle le player ?
> 
> Comment faire pour modifier le volume ?

Hello,
Pour Siri je ne sais pas encore je cherche, mais pour le volume si vous utilisez la télécommande du centre de contrôle, les boutons volume de l'iPhone contrôleront le volume de la Freebox.
Chez moi la touche "Retour" ne marche pas, et ca ne marche pas non plus quand j'essaie avec Postman avec cette adresse alors que les autres boutons marchent : http://my-freebox-ip/pub/remote_control?code=code-remote&key=back. Est ce que c'est pareil pour vous ?

**Comment by anthouny** [comment]
Hello, idem pour moi la touche retour ne marche pas, idem aussi via l'url. Ca doit être autre chose que "back". Est-ce que le développeur peut nous répondre ?

As-tu trouver d'autres astuces ?

**Comment by securechicken** [comment]
@anthouny Hi. This repository contains code for a Homebrige module that simply wraps some poorly documented "REST API" like commands for Freebox Player remote. It is left as-is to the community, has been developed in my spare time as a proof of concept, and suited my needs back then. The "issues" tracker of the repository is aimed at tracking development issues. For any question or support on Apple products, please reach Apple or its users communities. I understand this might be frustrating, but opening this issue here is like asking a car engine ignition engineer how to turn the volume up on the car music system. I personally don't use Siri and don't know.

@DavidMaarek Hi, thanks having answered another user support request. The "BACK" button does not work for me either, but is sending the only remote "key" I could find that looked like it would do that. Unfortunately, it is either a Freebox player bug (on an undocumented API, so will probably not be fixed), or the "key" to be used to achieve a "BACK" action is another one, and is yet to be found. You did right trying to send codes directly with a HTTP request. Try other keywords (I remember I did one or two attempts, but did not have more time to check), and if you ever find the correct one, feel free to open a new issue, I would fix the module code with it.

**Comment by anthouny** [comment]
@securechicken Merci, le bouton retour fonctionne maintenant :)

**Comment by anthouny** [comment]
Est-il possible d'ajouter des fonctions ?
