### ISSUE TITLE
[REQ] Freebox révolution

### ISSUE THREAD

**Issue by Louison-B** [securechicken/homebridge-freebox-player-delta#2]
I tested this plugin with my Freebox Révolution because the "Freemote" plugin works only for channel change. He doesn't works for ON/OFF function.

This plugin works for ON/OFF function but he doesn't works with "Home", "TV", "Netflix", "Youtube", "Media". There is a way to patch this plugin to be able to use the last enumerate function ?

Thank you in advance.

Greetings,

**Comment by securechicken** [comment]
Hi @Louison-B ,
This issue seems to be related to an unsupported version - this plugin is aimed at controlling the Freebox Player Delta only. No development will be made to fit an unsupported version - as the plugin is open source, you are however free to fork the code and develop a Freebox Revolution version based on it.
If your issue is encountered with a Freebox Player Delta, please open a bug-type issue, and provide required information as requested in the issue template.
